# an object describing our player
player = { "name": "p1", "score": 0,"items" : ["milk"],"friends" : [],"location" : "start"}
rooms = {"room1" : "a forest clearing","room2" : "a forest path","room3" : "an alternate path"}

import random # random numbers
import sys # system stuff for exiting

#----------------------------------------------------------------------------------------------------------------

def rollDice(minNum, maxNum, difficulty):
    # any time a chance of something might happen, let's roll a dice
    result = random.randint(minNum,maxNum)
    return result

#----------------------------------------------------------------------------------------------------------------

def graphicLibrary(name):
    if (name=="startPage"):        
        print("   ██╗    ██╗ ██████╗ ██████╗ ██╗     ██████╗     ██████╗ ███████╗███████╗███████╗███╗   ██╗██████╗ ███████╗██████╗ ") 
        print("   ██║    ██║██╔═══██╗██╔══██╗██║     ██╔══██╗    ██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██╔══██╗██╔════╝██╔══██╗") 
        print("   ██║ █╗ ██║██║   ██║██████╔╝██║     ██║  ██║    ██║  ██║█████╗  █████╗  █████╗  ██╔██╗ ██║██║  ██║█████╗  ██████╔╝") 
        print("   ██║███╗██║██║   ██║██╔══██╗██║     ██║  ██║    ██║  ██║██╔══╝  ██╔══╝  ██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██╔══██╗") 
        print("   ╚███╔███╔╝╚██████╔╝██║  ██║███████╗██████╔╝    ██████╔╝███████╗██║     ███████╗██║ ╚████║██████╔╝███████╗██║  ██║") 
        print("    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═════╝     ╚═════╝ ╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚═╝  ╚═╝") 
        print("")
        print("")     
        print("                      ..MNNNNNNNNM:.                                             ")    
        print("                  . DMNNNN~N.NN NNNMNN.MNM. .                             ")                 
        print("                 NNI..N,.N   .NM     ...  .,M7                                    ")                 
        print("              $MN.++.     MDN. D.  M,.?.  MN+,NN..                        ")             
        print("           .8N.N.NNNNM.    .N..N ..NN.N. ,DNN.NN,N.                         ")           
        print("          .M.?,MN....DN.    .M.. M.. NNN.N  ,N.NM.,N                         ")          
        print("        .N.  ?..        .         .N:NN.MN     NN.M$N?                         ")        
        print("      ..N.MN.N.       NNN          DM~ .N$.      NN  .N                         ")       
        print("     .,N.M.D          NM.              NN        NM   .N.                         ")     
        print("     .M . .             N              .ND  ..    N    .N                            ")  
        print("    .N..N.               N                .NNNN.     .   N.                           ") 
        print("   .NNM..               .N               .MM..N.     MN  NN                           ") 
        print("   N?.                   N              D.   $.      MNND..:      Hero! Your Mission is to Defend our Earth!                         ") 
        print("  .N.+                  N         .    .               .N. N.                           ") 
        print("  NN                    ,N       .I.NN  N                N.N.                         ") 
        print("  N.                    .N       .N. ..M .               .N.N                         ") 
        print("  N                    NM         .. D  ..            I.  M.N                        ") 
        print("  N                   .N.             N.               N  N.N                         ") 
        print("  N                     .D       ... .N. ..               ..N                         ") 
        print("  N                       =,     N.. ..D  MN=NN.      .D. .NN     By Frank Gong                       ") 
        print("  N                         .NM.  NNN  :  .N.,.?M      NN Z.N.                        ") 
        print("  N                             M ..D ..          N    ZM .,M                         ") 
        print("  M.                             .  N .M .N.NNDN. ..      .NM                         ") 
        print("  ZN                                   .N7..  ..N      N.M N.                         ") 
        print("   N                                   . N       .NNN  NN7NM                          ") 
        print("   ?D                                .N..          .,NN, .N.              ") 
        print("    M.  +N                           .M.               M.NN                           ") 
        print("     N.  M.                           =,             .N..N                ") 
        print("    ..N  N.                            N            N  .N                 ") 
        print("      .NN.M                             ~NN .      N   M                  ") 
        print("      ..N...   .                          .N      N. =N                   ") 
        print("         NO.N.ND.                         N.    .N..N.                    ") 
        print("         ..M.+NM ND                       N.  ..D.NN                      ") 
        print("           .NN.  .N                      N ..NM.NM.                       ") 
        print("             ..N  MMNNN..,              N, .N,NN                          ") 
        print("                .NNN  N..N..          .N.NNNN.                           ") 
        print("                     NNNNN NNN     ...NNNO                                ") 
        print("                          .,NN$7.. ...                                    ")
        
#----------------------------------------------------------------------------------------------------------------
def gameOver():
    print("You Die, Earth too...")
    return

#-------------------------------------------------------------------------------------------------------------
def scene2():
    print("                         & ")                        
    print("                         } ")                        
    print("                         } ")                       
    print("                         } ")                        
    print("                      ^/d$k/^ ")                     
    print("                    x$$$$$$$$$x ")                   
    print("                   d$$$$$$$$$$$b ")                  
    print("                   $$$$$$$$$$$$$ ")                  
    print("                   $$)@$$)$$$[$$ ")                  
    print("                   $+  $i l$  i$ ")                  
    print("                   $$+B$$<a$$~$$ ")                  
    print("                   $$$$$$$$$$$$$ ")                 
    print("                U8$$$$$$$$$$$$$$$%C ")               
    print("            -$$$$$$$$$$$$$$$$$$$$$$$$$] ")           
    print("          L$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O ")         
    print("         $/$Z$%$$#$O$c$Y$C$c$r$C$o$$$$w$r$ ")       
    print("         ddddpdddQZdddddddddddddddddddpddd` ")      
    print("         t$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$f ")        
    print("           @$$$$$$$$$$$$$$$$$$$$$$$$$$$$' ")         
    print("             [J$$$$$$$$$$$$$$$$$$$$$w{ ")            
    print("                  `$i:::;:::::!$` ")                 
    print("                    wY:     ,Xp ")                   
    print("                     '?JW@WC?   ")
    print(" ")
    print(" ")
    print("From the window, I see two alien spaceships in the sky are approaching quickly. I am thinking about what I can do.")
    decision2=input("You can choose: CALL UN SECURITY COUNCIL/CALL 911/WEAR PERFUME/EAT DURIAN > ")

    if(decision2=="CALL UN SECURITY COUNCIL"):
        print("Calling UN SECURITY COUNCIL...Please be patient")
        input("Press enter > ")

        roll=rollDice(0,20,10)

        if(roll>=10):
            print("Calling Successful!")
            input("Press enter > ")
            print("                                               $$$$")
            print("                                             $$$$$$$")
            print("                                           $$$$$$$$$")
            print("                                       $$$$$$$$$$$ ")
            print("                                     $$$$$$$$$$$   ")
            print("                                    $$$$$$$$$$$    ")
            print("                                  $$$$$$$$$$$$$    ")
            print("                                $$$$$$$$$$$$$      ")
            print("                               $$$$$$$$$$$$$       ")
            print("                             $$$$$$$$$$$$$$        ")
            print("                            $$$$$$$$$$$$$          ")
            print("                          $$$$$$$$$$$$$            ")
            print("                        $$$$$$$$$$$$$$             ")
            print("                       $$$$$$$$$$$$$               ")
            print("                     $$$$$$$$$$$$$$                ")
            print("                    $$$$$$$$$$$$$                  ")
            print("                  $$$$$$$$$$$$$                    ")
            print("                $$$$$$$$$$$$$$                     ")
            print("               $$$$$$$$$$$$$                       ")
            print("             $$$$$$$$$$$$$$                        ")
            print("     $$     $$$$$$$$$$$$$                          ")
            print("   $$$$$$$$$$$$$$$$$$$$$                           ")
            print(" $$$$$$$$$$$$$$$$$$$$$                             ")
            print("$$$$$$$$$$$$$$$$$$$$                               ")
            print("$$$$$$$$$$$$$$$$$$$                                ")
            print("$$$$$$$$$$$$$$$$$                                  ")
            print("      $$$$$$$$$$$$                                 ")
            print("        $$$$$$$$$$                                 ")
            print("         $$$$$$$$$$                                ")
            print("         $$$$$$$$$                                 ")
            print("          $$$$$$                                   ")
            print("          $$$$$")
            print("")
            print("")
            print("After I described what I saw, the members of the Security Council immediately launched thousands of nuclear Missiles at the alien spacecraft, and the Earth is saved.")
            print("Congratulation，"+player["name"]+"！You get the best earth citizen title！")
            return
        
        else:
            print("Calling Failed!")
            input("Press enter > ")
            scene2()
            
    elif(decision2=="CALL 911"):
        print("Calling 911...Please be patient")
        input("Press enter > ")

        roll=rollDice(0,20,5)

        if(roll>=5):
            print("Calling Successful!")
            input("Press enter > ")
            print("But 911 thinks you are kidding.")
            scene2()
        else:
            print("Calling Failed!")
            input("Press enter > ")
            scene2()
            
    elif(decision2=="WEAR PERFUME"):
        
        roll=rollDice(0,20,10)

        if(roll>=10):
            print("               .i{xCpho*##oapLu1>` ")              
            print("           'jh#########***#########au^ ")           
            print("        ido######pU1"       "{Xp*#####ob+         ")
            print("      nb###*q)                   `[Z*###hc       ")
            print("    th###m[                           _Q*##ax     ")
            print("  ;m###0;                               `U*##p>   ")
            print(" +###h                                     b###}  ")
            print("~*##v                                       j##*[ ")
            print("a##v                                         f*#o ")
            print("n##m,                                          Q##z")
            print("h#*x      n*###h]                 ?h###*x      (*#a")
            print("##*/     *#######o_             +h#######*     [o##")
            print("a#*j    b##Q` 'm##of           (a##d: .U##a    1*#a")
            print("m##X    h##x    z##h}         -k##C    (o##    x##w")
            print(")##q;   h##x     L##m'        0##Z     )o##   'Z##t")
            print(" M#*}   h##c      a##|       }##o      j##M   -*## ")
            print(" u##q^  u##a]     Y##Y       v##Q     >h##t   w##c ")
            print("  k##u   a##m^    i##q`      p##_     O##b   n##d  ")
            print("  <*#*1   h##w!    *#aI      a#*'   :m##b.  )##o+  ")
            print("   /*##+   d###/   o#al     ;*#*   1###p.  [##*/   ")
            print("    j###u   z####U.o#al     :*#*'c####z   X###r    ")
            print("     u*##J   !m######d'     `h######wl   J*#*n     ")
            print("      1a##d!   ;C####c       n####0!   !p##o[      ")
            print("       ~k##ox     }v(         )v}     x###pI ")      
            print("         O*##h!                     i*##*X ")        
            print("          'a###q                  p###p^ ")         
            print("            1k###Q<             -Z###p-   ")         
            print("              th##*O~         _Z###h) ")             
            print("                xb###k/     fa###pr ")               
            print("                  +a####kuh####h> ")                 
            print("                     uo#####au ")                    
            print("                       ~YaJ~             ")
            print("")
            print("")
            print("You wear a bottle of perfume and then accidentally encounter the alien spaceships. \nThe aliens who are driving the spacecraft are allergic to perfume. \nThe alien spacecraft crashed because of the smell of perfume. \nEarth is safe!")
            input("Press enter > ")
            print("Congratulation，"+player["name"]+"！You earn the title of Earth Defender and received a lifetime free perfume privilege!")
            return
        else:
            print('   ')
            print('          >     ')                     
            print('   ')                                                 
            print('                               !   ')                 
            print('                  I    "  ` ``   ')                   
            print('                            :"   ')                   
            print('                  "+,     " ".          l {        ')
            print('        I         1I-^    I    1   ')                 
            print('      `  ~        ~l-`>   :    `        ;   ')        
            print('          <li      [: ^   "   _  I    `<  .         ')
            print('       "   <]l     ,    ^  `  ^`:    II^:l          ')
            print('        ^l  i+    `     i  ~   I!." I"l!.           ')
            print('          !: I"   I   . -  ^   - l ..l:i_:          ')
            print('    ,_"    `_ ^I   l .: [     l`|                   ')
            print('      ,/{    ^" I^<!  , 1    .:[             "`     ')
            print('    ;!   _i       "}+:" !"   < |I;    ;" `(j[       ')
            print('  ;^  _){I        `li[ l | `?  1^ :1}I              ')
            print('    Il`   "   .:   "      :"    ":l^                ')
            print('               l(<:^           .  <                 ')
            print('            .,;~ti                ,l;:^             ')
            print('           `>?}(t|il!i>>>>ii!iii:"i]->l,  ')
            print("")
            print("")    
            print("You wear a bottle of perfume and then accidentally encounter the alien spaceships. \nThe aliens who are driving the spacecraft are allergic to durian. \nBecause of the smell of perfume, alien spaceships stun you.")
            decision2=input("press enter > ")
            gameOver()

    elif(decision2=="EAT DURIAN"):

        roll=rollDice(0,20,10)

        if(roll>=10):
            print("               .i{xCpho*##oapLu1>` ")              
            print("           'jh#########***#########au^ ")           
            print("        ido######pU1"       "{Xp*#####ob+         ")
            print("      nb###*q)                   `[Z*###hc       ")
            print("    th###m[                           _Q*##ax     ")
            print("  ;m###0;                               `U*##p>   ")
            print(" +###h                                     b###}  ")
            print("~*##v                                       j##*[ ")
            print("a##v                                         f*#o ")
            print("n##m,                                          Q##z")
            print("h#*x      n*###h]                 ?h###*x      (*#a")
            print("##*/     *#######o_             +h#######*     [o##")
            print("a#*j    b##Q` 'm##of           (a##d: .U##a    1*#a")
            print("m##X    h##x    z##h}         -k##C    (o##    x##w")
            print(")##q;   h##x     L##m'        0##Z     )o##   'Z##t")
            print(" M#*}   h##c      a##|       }##o      j##M   -*## ")
            print(" u##q^  u##a]     Y##Y       v##Q     >h##t   w##c ")
            print("  k##u   a##m^    i##q`      p##_     O##b   n##d  ")
            print("  <*#*1   h##w!    *#aI      a#*'   :m##b.  )##o+  ")
            print("   /*##+   d###/   o#al     ;*#*   1###p.  [##*/   ")
            print("    j###u   z####U.o#al     :*#*'c####z   X###r    ")
            print("     u*##J   !m######d'     `h######wl   J*#*n     ")
            print("      1a##d!   ;C####c       n####0!   !p##o[      ")
            print("       ~k##ox     }v(         )v}     x###pI ")      
            print("         O*##h!                     i*##*X ")        
            print("          'a###q                  p###p^ ")         
            print("            1k###Q<             -Z###p-   ")         
            print("              th##*O~         _Z###h) ")             
            print("                xb###k/     fa###pr ")               
            print("                  +a####kuh####h> ")                 
            print("                     uo#####au ")                    
            print("                       ~YaJ~             ")
            print("")
            print("")
            print("You eat five big durians and then accidentally encounter the alien spaceships. \nThe aliens who are driving the spacecraft are allergic to durian. \nThe alien spacecraft crashed because of the smell of durian. \nEarth is safe!")
            input("Press enter > ")
            print("Congratulation，"+player["name"]+"！You earn the title of Earth Defender and received a lifetime free privilege of unlimited durian!")
            return
        else:
            print('   ')
            print('          >     ')                     
            print('   ')                                                 
            print('                               !   ')                 
            print('                  I    "  ` ``   ')                   
            print('                            :"   ')                   
            print('                  "+,     " ".          l {        ')
            print('        I         1I-^    I    1   ')                 
            print('      `  ~        ~l-`>   :    `        ;   ')        
            print('          <li      [: ^   "   _  I    `<  .         ')
            print('       "   <]l     ,    ^  `  ^`:    II^:l          ')
            print('        ^l  i+    `     i  ~   I!." I"l!.           ')
            print('          !: I"   I   . -  ^   - l ..l:i_:          ')
            print('    ,_"    `_ ^I   l .: [     l`|                   ')
            print('      ,/{    ^" I^<!  , 1    .:[             "`     ')
            print('    ;!   _i       "}+:" !"   < |I;    ;" `(j[       ')
            print('  ;^  _){I        `li[ l | `?  1^ :1}I              ')
            print('    Il`   "   .:   "      :"    ":l^                ')
            print('               l(<:^           .  <                 ')
            print('            .,;~ti                ,l;:^             ')
            print('           `>?}(t|il!i>>>>ii!iii:"i]->l,  ')
            print("")
            print("")    
            print("You eat five big durians and then accidentally encounter the alien spaceships. \nThe aliens who are driving the spacecraft are allergic to perfume. \nBecause of the smell of durian, alien spaceships stun you.")
            decision2=input("press enter > ")
            gameOver()
            
    else:
        print("Take the right action!")
        decision2=input("press enter > ")
        scene2()

#----------------------------------------------------------------------------------------------------------------
def scene1():
    print("                ~Zx }       ")                          
    print("              Cd J^-z       ")                             
    print("            Z^U !&]Qr       ")                            
    print("           z ?)z/  ]):       ")                            
    print("           >jM<<J wu'|       ")                            
    print("            l. zxtr 1b  ")                          
    print("            J~CL _:-d;  ")                          
    print("            [ Y.~&cu/ v      :  ")                  
    print("              }U/  1Ihw     ~'  ")                  
    print("             $.+w u* r     { (~  ")                 
    print("             _ tZ?p {cwu     -Y  ")                 
    print("              Yz i:)Z: j  Q  + +/  ")              
    print("              C.+@}tj pu  I   i_} ?  ")             
    print("              {|X` u?j-'  !   )MYlI  ")            
    print("              ^ J 1Lu?ji? I   ); `  ")              
    print("               x(j f1   Ob_     '    ")            
    print("                 ni     jLo    ud  ")               
    print("              (wx-      <Q >   n^    ")            
    print("            ;l  Zw       ~  [    .  ")              
    print("            k   !      ()    {zxr`  ")              
    print("            i    'c  z[lc]?  ")                     
    print("           (/t   k{)-QJn _0  ")                     
    print("           t0B  >! ]b^>:iO(    ")                     
    print("             ^1u  CU':$XYx 1  ")                    
    print("                   [)O  } La  ")                    
    print("                  $-la _M'f  ")                     
    print("                  I [/zp ?nv_  ")                   
    print("                   vb.ll^k<.Y  ")                   
    print("                   0.'$fnn Cz  ")                   
    print("                   _)CI x,xU'I  ")                  
    print("                   I m [U[(  x  ")                  
    print("                    t~Up ;m-Mr  ")                  
    print("                    u >:.h1 {~  ")                  
    print("                    n $h+L (-Q  ")                  
    print("                     z. v cv  ")                    
    print("                     [ [L>  ")                      
    print("                     ,|<  ")
    print("")
    print("")
    print("")
    print("'Jeez! I am now working in the International Space Station. \nI see two alien spaceships are flying to Manhattan! ' Jack said in horror, then dropped the line.")
    decision1=input("You can choose: WHAT SHOULD I DO/I AM IN NJ/BORING > ")

    if(decision1=="WHAT SHOULD I DO"):
        scene2()
        
    elif(decision1=="I AM IN NJ"):
        print('   ')
        print('          >     ')                     
        print('   ')                                                 
        print('                               !   ')                 
        print('                  I    "  ` ``   ')                   
        print('                            :"   ')                   
        print('                  "+,     " ".          l {        ')
        print('        I         1I-^    I    1   ')                 
        print('      `  ~        ~l-`>   :    `        ;   ')        
        print('          <li      [: ^   "   _  I    `<  .         ')
        print('       "   <]l     ,    ^  `  ^`:    II^:l          ')
        print('        ^l  i+    `     i  ~   I!." I"l!.           ')
        print('          !: I"   I   . -  ^   - l ..l:i_:          ')
        print('    ,_"    `_ ^I   l .: [     l`|                   ')
        print('      ,/{    ^" I^<!  , 1    .:[             "`     ')
        print('    ;!   _i       "}+:" !"   < |I;    ;" `(j[       ')
        print('  ;^  _){I        `li[ l | `?  1^ :1}I              ')
        print('    Il`   "   .:   "      :"    ":l^                ')
        print('               l(<:^           .  <                 ')
        print('            .,;~ti                ,l;:^             ')
        print('           `>?}(t|il!i>>>>ii!iii:"i]->l,  ')
        print("")
        print("")               
        print("…An alien spacecraft suddenly diverted to New Jersey...and then a harsh sound in the sky, then...THE EARTH IS DESTROYED！")
        decision1=input("Press enter > ")
        gameOver()
        
    elif(decision1=="BORING"):
        print('   ')
        print('          >     ')                     
        print('   ')                                                 
        print('                               !   ')                 
        print('                  I    "  ` ``   ')                   
        print('                            :"   ')                   
        print('                  "+,     " ".          l {        ')
        print('        I         1I-^    I    1   ')                 
        print('      `  ~        ~l-`>   :    `        ;   ')        
        print('          <li      [: ^   "   _  I    `<  .         ')
        print('       "   <]l     ,    ^  `  ^`:    II^:l          ')
        print('        ^l  i+    `     i  ~   I!." I"l!.           ')
        print('          !: I"   I   . -  ^   - l ..l:i_:          ')
        print('    ,_"    `_ ^I   l .: [     l`|                   ')
        print('      ,/{    ^" I^<!  , 1    .:[             "`     ')
        print('    ;!   _i       "}+:" !"   < |I;    ;" `(j[       ')
        print('  ;^  _){I        `li[ l | `?  1^ :1}I              ')
        print('    Il`   "   .:   "      :"    ":l^                ')
        print('               l(<:^           .  <                 ')
        print('            .,;~ti                ,l;:^             ')
        print('           `>?}(t|il!i>>>>ii!iii:"i]->l,  ')
        print("")
        print("") 
        print("You dream for half an hour, and then there's a screech in the sky, and then... ")
        print("THE EARTH IS DESTROYED!")
        decision1=input("press enter > ")
        gameOver()
        
    else:
        print("I don't understand...")
        decision1=input("Press enter > ")
        scene1()
    
#----------------------------------------------------------------------------------------------------------------
def introduction():
    
    print("Hero! What's your name?")
    player["name"]=input("Please enter your name >")
    
    print("Welcome! Hero. "+player["name"]+"!")
    print("")
    print("      BM***********************8@    ")
    print("     8bdhaaaaaaaaaaaaaaaaaaaaakp#@   ")
    print("    $ob8                      $#b8   ")
    print("    @hh@  $@@@@@$    $@@@@@@$  Wd&   ")
    print("    @hh@Bhqwwwwwp*@ 8kqwwwwqdM Wd&   ")
    print("    @hh@oZOOOOOOOqW$kZOOOOOOOd%Wd&   ")
    print("    @hh@aZOOOOOOOwM@kOOOOOOOOp8Wd&   ")
    print("    @hb&kZOOOOOOOwo8dOOOOOOOOqM*d&   ")
    print("    BbOOOOOOOOOOOOOOOOOOOOOOOOOOZW$  ")
    print("    8qOOOOOOOOOOOOOOOOOOOOOOOOOOOo@  ")
    print("    WZOOOOOOOOOOOOOOOOOOOOOOOOOOOkB  ")
    print("   @*OOOOOOOOOOOOOOOOOOOOOOOOOOOOq8  ")
    print("   BkOOOOOOOOOOOOOOOOOOOOOOOOOOOOZ&$ ")
    print("   %pOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*@ ")
    print("  $&woB@@@@@@@@@@@@@@@@@@@@@@@@@&pk@ ")
    print("  @#dB                           *dB ")
    print("  @*d@                           #pB ")
    print("  @*q*###########################kpB ")
    print("  @*waaaaaaaaaaaaaaaaaaaaaaaaaaaadqB ")
    print("  @*d@$$$$$$$$$$$$$$$$$$$$$$$$$$$#pB ")
    print("  @#k@                           MbB ")
    print("   $$                            $$")
    print("")
    print("")
    print("It's 1 pm, you're lying on bed.")
    print("And you seem to have completely forgotten that there's a coding class at 2PM...")
    input("Press enter > ")
    print("")
    print("              ~XvuuuuuuuuuuuuuuuuuuuvY_ ")            
    print("             U                       z^ ")           
    print("            .U        ^>>>>>,        u: ")           
    print("            .U ;>>>>>>>>>>>>>>>>>>>; u: ")           
    print("            vU{                     (u:")            
    print("            .U[                     1u:")            
    print("            ?U[                     1u{")            
    print("            UU[                     1uL")            
    print("            ?U[                     1uJ")            
    print("            XU[                     1u:")            
    print("            XU[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")                                  
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U[                     1u:")            
    print("            .U{                     (u:")            
    print("            .U <>>>>>>>>>>>>>>>>>>>~.u:")            
    print("            .U          (~)          u:")            
    print("             U          (~)          z^")            
    print("             ~XvuuuuuuuuuuuuuuuuuuuvY_ ")
    print("")
    print("")
    
    print("Suddenly, the new iphone 11 pro you bought yesterday rings.")
    print("It's your best friend Jack who you haven't seen in six months. ")
    
    decision=input("You can choose: ANSWER THE PHONE/BACK TO SLEEP > ")
    if(decision == "ANSWER THE PHONE"):
        print("You take the phone from Jack")
        input("Press enter > ")
        scene1()
        
    elif(decision == "BACK TO SLEEP"):
        print('   ')
        print('          >     ')                     
        print('   ')                                                 
        print('                               !   ')                 
        print('                  I    "  ` ``   ')                   
        print('                            :"   ')                   
        print('                  "+,     " ".          l {        ')
        print('        I         1I-^    I    1   ')                 
        print('      `  ~        ~l-`>   :    `        ;   ')        
        print('          <li      [: ^   "   _  I    `<  .         ')
        print('       "   <]l     ,    ^  `  ^`:    II^:l          ')
        print('        ^l  i+    `     i  ~   I!." I"l!.           ')
        print('          !: I"   I   . -  ^   - l ..l:i_:          ')
        print('    ,_"    `_ ^I   l .: [     l`|                   ')
        print('      ,/{    ^" I^<!  , 1    .:[             "`     ')
        print('    ;!   _i       "}+:" !"   < |I;    ;" `(j[       ')
        print('  ;^  _){I        `li[ l | `?  1^ :1}I              ')
        print('    Il`   "   .:   "      :"    ":l^                ')
        print('               l(<:^           .  <                 ')
        print('            .,;~ti                ,l;:^             ')
        print('           `>?}(t|il!i>>>>ii!iii:"i]->l,  ')
        print("")
        print("") 
        print("You dream for half an hour, and then there's a screech in the sky, and then... ")
        print("THE EARTH IS DESTROYED!")
        decision=input("Press enter > ")
        gameOver()

    else:
        print("I don't understand...")
        decision=input("Press enter > ")
        introduction()
        
#----------------------------------------------------------------------------------------------------------------
def main():
    graphicLibrary("startPage")
    introduction()
main()
    
